import React, { useEffect, useRef, useState } from 'react';
import * as api from '../api/briefApi';

/** A reason is entered by the reviewer, never pre-filled or generated by a CTA. */
export function SpaceModerationPanel() {
  const [queue, setQueue] = useState<api.SpaceModerationQueue | null>(null);
  const [error, setError] = useState('');
  const [notice, setNotice] = useState('');
  const [version, setVersion] = useState(0);
  const [reasons, setReasons] = useState<Record<string, string>>({});
  const [busy, setBusy] = useState(false);
  // Retain the key for an identical retry after a lost response. A changed
  // action, target, hold revision or reason is a different request.
  const retries = useRef(new Map<string, string>());
  useEffect(() => {
    let live = true;
    setError('');
    api.getSpaceModerationQueue().then(r => {
      if (!live) return;
      if (r.ok) setQueue(r.data);
      else { setQueue(null); setError(r.error); }
    });
    return () => { live = false; };
  }, [version]);
  const run = async (id: string, action: 'upheld' | 'dismissed' | 'reinstate', holdId?: string) => {
    const reason = (reasons[id] ?? '').trim();
    if (!reason || busy) return;
    const signature = JSON.stringify({ id, action, holdId, reason });
    let key = retries.current.get(signature);
    if (!key) {
      key = globalThis.crypto?.randomUUID?.() ?? `mod-${Date.now()}-${Math.random().toString(36).slice(2)}`;
      retries.current.set(signature, key);
    }
    setBusy(true); setError(''); setNotice('');
    const result = action === 'reinstate'
      ? await api.reinstateSpacePage(id, holdId!, reason, key)
      : await api.reviewSpaceReport(id, action, reason, key);
    setBusy(false);
    if (!result.ok) { setError(result.error); return; }
    setNotice(result.data.replayed ? 'The earlier action was already saved. Current state has been refreshed.' : action === 'reinstate' ? 'Page reinstated. Accounts, orders and reward restrictions were not changed.' : action === 'upheld' ? 'Report upheld; public page hidden. Selling, orders and reward restrictions were not changed.' : 'Report dismissed. Page visibility and reward restrictions were not changed.');
    setReasons(old => ({ ...old, [id]: '' }));
    setVersion(v => v + 1);
  };
  const reasonField = (id: string, label: string) => <label className="block text-sm font-bold">{label}<textarea aria-label={label} required maxLength={1000} disabled={busy} value={reasons[id] ?? ''} onChange={e => setReasons(old => ({ ...old, [id]: e.target.value }))} className="block w-full rounded-xl p-3 mt-1" placeholder="Explain your decision. Required; stored in the audit trail." /></label>;
  const buttonClass = 'rounded-xl px-4 py-2 text-sm font-bold bg-[var(--color-primary)] text-white disabled:opacity-40';
  return <section aria-label="Public page moderation" className="space-y-5">
    <p className="text-sm">Reviewers and admins only; no self-review. Upheld reports hide the public page only. Appeals and guardian reward decisions are separate.</p>
    {error && <p role="alert" className="text-sm text-red-700">{error} <button disabled={busy} className="underline font-bold" onClick={() => setVersion(v => v + 1)}>Reload queue</button></p>}
    {notice && <p role="status" className="text-sm font-bold">{notice}</p>}
    {!queue && !error && <p role="status">Loading reports…</p>}
    {queue && <>
      <section aria-label="Reported pages" className="space-y-3"><h3 className="text-lg font-bold">Reports</h3>
        {!queue.reports.length && <p className="text-sm">No page reports.</p>}
        {queue.reports.map(r => <article key={r.id} className="p-4 rounded-2xl bg-[var(--color-paper)] space-y-3">
          <h4 className="font-bold">{r.spaceName} · {r.outcome}</h4>
          <p className="text-sm whitespace-pre-wrap">{r.reason}</p>
          <p className="text-xs">Reported {r.createdAt}</p>
          {r.handledAt && <p className="text-sm">Reviewed {r.handledAt} by {r.handledBy}. Reason: {r.moderationReason}</p>}
          {r.canReview && <>
            {reasonField(r.id, `Review reason for ${r.spaceName}`)}
            <div className="flex flex-wrap gap-2">
              <button className={buttonClass} disabled={busy || !reasons[r.id]?.trim()} onClick={() => void run(r.id, 'upheld')}>Uphold & hide page</button>
              <button className={buttonClass} disabled={busy || !reasons[r.id]?.trim()} onClick={() => void run(r.id, 'dismissed')}>Dismiss report</button>
            </div>
          </>}
          {r.outcome === 'pending' && !r.canReview && <p className="text-sm">This report needs another authorized reviewer.</p>}
        </article>)}
      </section>
      <section aria-label="Hidden pages" className="space-y-3"><h3 className="text-lg font-bold">Hidden public pages</h3>
        {!queue.hiddenPages.length && <p className="text-sm">No pages are currently held by moderation.</p>}
        {queue.hiddenPages.map(p => <article key={p.id} className="p-4 rounded-2xl bg-[var(--color-paper)] space-y-3">
          <h4 className="font-bold">{p.name}</h4><p className="text-sm">Hidden {p.hiddenAt}. Shop status: {p.status}.</p>
          {p.canReinstate ? <>{reasonField(p.id, `Reinstatement reason for ${p.name}`)}<p className="text-sm">This explicitly republishes the page. It does not reverse the report outcome or clear unrelated restrictions.</p><button className={buttonClass} disabled={busy || !reasons[p.id]?.trim()} onClick={() => void run(p.id, 'reinstate', p.holdId)}>Reinstate public page</button></> : <p className="text-sm">Reinstatement requires an active shop and a reviewer who is not its owner.</p>}
        </article>)}
      </section>
    </>}
  </section>;
}
