// ---------------------------------------------------------------------------
// UNIFIED INBOX — per-contact conversation projection (CCS §3.2)
//
// The communication hub's read side. Brief ingests from Telegram/WhatsApp/web
// and can send outbound; this module assembles, per resolved person, the
// chronological thread of what a creator and that contact have exchanged —
// inbound messages, outbound sends, and notifications — without inventing any
// message that did not occur.
//
// A "contact" is a person (domain/person.js). Messages come from three real
// sources, each tagged with its direction:
//   inbound   rawItems the ingest connectors wrote (telegram/whatsapp/web/manual)
//   outbound  outbound sends recorded when a blast/send fires
//   note      notifications generated by Brief (workflow, confirmations)
//
// Nothing here fakes a conversation; an empty thread is the honest answer.
// ---------------------------------------------------------------------------

import { store } from '../store.js';
import * as person from './person.js';

export function listContacts({ limit = 100 } = {}) {
  const contacts = new Map();
  // People with inbound activity.
  for (const raw of store.all('rawItems')) {
    const who = raw.author ?? 'Unknown';
    const key = `author:${String(who).toLowerCase()}`;
    if (!contacts.has(key)) {
      contacts.set(key, {
        key,
        kind: 'author',
        name: who,
        lastAt: raw.publishedAt ?? raw.createdAt,
        inboundCount: 0
      });
    }
    contacts.get(key).inboundCount++;
    const at = raw.publishedAt ?? raw.createdAt;
    if (String(at) > String(contacts.get(key).lastAt)) contacts.get(key).lastAt = at;
  }
  // People with a person row (account/participant).
  for (const p of store.all('people')) {
    const key = `person:${p.id}`;
    if (!contacts.has(key)) {
      contacts.set(key, { key, kind: 'person', name: p.displayName ?? p.id, lastAt: p.updatedAt, inboundCount: 0 });
    }
  }
  return Array.from(contacts.values())
    .sort((a, b) => String(b.lastAt).localeCompare(String(a.lastAt)))
    .slice(0, limit);
}

/** The conversation thread with one contact (inbound + outbound + notes). */
export function thread(contactKey) {
  const [kind, ...rest] = contactKey.split(':');
  const value = rest.join(':');
  const events = [];

  if (kind === 'author') {
    for (const raw of store.all('rawItems')) {
      if (String(raw.author ?? '').toLowerCase() !== value.toLowerCase()) continue;
      events.push({
        id: raw.id,
        direction: 'inbound',
        text: raw.text,
        at: raw.publishedAt ?? raw.createdAt,
        channel: raw.platform ?? 'unknown'
      });
    }
  } else if (kind === 'person') {
    const p = person.getPerson(value);
    const userIds = new Set((p?.aliases ?? []).filter((a) => a.kind === 'user').map((a) => a.value));
    for (const n of store.all('notifications')) {
      if (userIds.has(n.userId)) {
        events.push({ id: n.id, direction: 'note', text: n.title + (n.body ? ` — ${n.body}` : ''), at: n.createdAt, channel: 'brief' });
      }
    }
  }

  // Outbound sends to this contact are recorded by the distribution seam; the
  // store does not yet persist them, so an honest empty here is correct.
  return events.sort((a, b) => String(a.at).localeCompare(String(b.at)));
}
